import { button, buttonGhost, lede, sectionTag, sectionTitle, wrap } from "../app/global.css.ts";
import { Diagram } from "./Diagram.tsx";
import * as s from "./landing.css.ts";

const features = [
  {
    key: "01",
    title: "Events",
    text: "Dynamic events with typed properties, sessions and identity merge. Anonymous first, identified later, history intact.",
  },
  {
    key: "02",
    title: "Funnels, retention, cohorts",
    text: "Declared next to the project in configuration, down to the property values an event must carry and the numbers to sum. Each declaration becomes a reporting view and a panel in the project's own dashboard; nothing is written in SQL.",
  },
  {
    key: "03",
    title: "Crash tracking",
    text: "Fingerprinted issues with open, resolved and regressed states, crash-free users and sessions, breadcrumbs from the session's own events.",
  },
  {
    key: "04",
    title: "Consent ledger",
    text: "Every grant and withdrawal recorded with its policy version. Two purposes: analytics and diagnostics.",
  },
  {
    key: "05",
    title: "Erasure",
    text: "In-app erasure scoped to the device and its linked person, plus an operator function for requests that arrive by other means.",
  },
  {
    key: "06",
    title: "Inventory and manifest",
    text: "PRIVACY.md and the Apple privacy manifest are generated from the contract, so a field cannot be collected undeclared.",
  },
  {
    key: "07",
    title: "Everything in Grafana",
    text: "Eight shared dashboards, four alert rules, and a generated dashboard per environment in its own folder, on a vanilla Grafana with the built-in PostgreSQL datasource.",
  },
  {
    key: "08",
    title: "One NixOS module",
    text: "The server, PostgreSQL with peer authentication, and Grafana provisioning. Projects are declared next to the products they measure, and ingest keys are generated by the service.",
  },
] as const;

const sdks = [
  {
    title: "Flutter",
    text: "iOS, Android, desktop and web. Error capture, lifecycle sessions, a durable queue, and an Apple privacy manifest shipped in the plugin.",
  },
  {
    title: "TypeScript in the browser",
    text: "gRPC-Web, IndexedDB queue, unhandled error capture, Global Privacy Control honoured as a denial.",
  },
  {
    title: "TypeScript in Node",
    text: "Native gRPC, file-backed queue, process error capture, per-request trackers for the users a backend serves.",
  },
  {
    title: "Haskell",
    text: "Records of functions for the application's Env, per-request trackers with the consent the backend holds, a stub server for tests.",
  },
] as const;

const vocabulary = [
  "start",
  "tracker",
  "subject",
  "with",
  "track",
  "identify",
  "reset",
  "people",
  "recordError",
  "attempt",
  "log",
  "span",
  "flush",
  "close",
  "consent",
  "erase",
  "diagnostics",
] as const;

const principles = [
  {
    key: "P1",
    title: "Consent before anything.",
    text: "SDKs persist nothing and open no connection until a purpose is granted. A denial sends nothing.",
  },
  {
    key: "P2",
    title: "The server refuses unconsented data.",
    text: "Every batch carries a consent snapshot. A defective client cannot store what was not granted.",
  },
  {
    key: "P3",
    title: "Configuration is declared.",
    text: "Projects, retention, cohorts and analytics are configuration; keys are generated. Triage and erasure are Grafana actions only its Admins can take. There is no admin UI of its own to secure.",
  },
  {
    key: "P4",
    title: "Nothing hidden from the operator.",
    text: "PostgreSQL holds the data, Grafana shows it, the migrations are readable SQL. No black box in the middle.",
  },
  {
    key: "P5",
    title: "Recording never breaks the app.",
    text: "A recording call never throws in release. Problems flow into one diagnostics stream.",
  },
  {
    key: "P6",
    title: "MIT, and yours to run.",
    text: "Self-hosted on your machine, your database, your dashboards. Easy to leave, nothing to export.",
  },
] as const;

const flutterSample = `final insights = await FlutterInsights.start(
  url: Uri.parse("https://insights.example.org"),
  key: key,
  consent: const ConsentPolicy.ask(),
);

final checkout = insights.tracker.with_({"screen": "checkout"});
await checkout.track("order_placed", {
  "total": 42.5,
  "items": 3,
});`;

const haskellSample = `withInsights config \\insights -> do
  let tracker = insights.subject subject consent
  track tracker "order_placed"
    ["total" =: 42.5, "items" =: (3 :: Int)]
  attempt tracker (placeOrder order)`;

export const Landing = () => (
  <>
    <div class={s.hero}>
      <div class={s.gridBg} aria-hidden="true" />
      <div class={wrap}>
        <div class={s.inner}>
          <span class={s.catTag}>
            <span class={s.catDot} aria-hidden="true" />
            Self-hosted · Analytics and crash tracking
          </span>
          <h1 class={s.title}>
            Insights<span class={s.titleDot}>.</span>
          </h1>
          <p class={s.tagline}>Product analytics and crash tracking with consent built in.</p>
          <p class={s.blurb}>
            A Haskell server over gRPC, PostgreSQL underneath, Grafana as the whole frontend. SDKs
            for <b>Flutter, TypeScript and Haskell</b> that persist nothing before consent and never
            break your app. Funnels, retention, cohorts, crash-free rates, a consent ledger and a
            generated privacy inventory, on your own machine.
          </p>
          <div class={s.ctas}>
            <a class={button} href="/docs">
              Read the docs <span aria-hidden="true">→</span>
            </a>
            <a class={buttonGhost} href="https://github.com/peculiar-systems/peculiar-insights">
              Source on GitHub <span aria-hidden="true">↗</span>
            </a>
          </div>
          <p class={s.trust}>MIT licensed. One NixOS module.</p>
          <div class={s.why}>
            <h2 class={s.whyTitle}>Why this exists</h2>
            <p class={s.whyText}>
              Hosted analytics asks you to ship your users' behaviour to someone else and to bolt
              consent on afterwards. Insights turns that around: consent is the first thing the SDK
              knows, the server refuses what was not granted, and the data stays in a database you
              own and can read with plain SQL.
            </p>
          </div>
        </div>
      </div>
    </div>

    <section class={s.section} id="what">
      <div class={wrap}>
        <p class={sectionTag}>What you get</p>
        <h2 class={sectionTitle}>The whole loop, from event to dashboard.</h2>
        <p class={lede}>
          Everything a product team asks a tracker for, and the parts a privacy officer asks for, in
          one deployment.
        </p>
        <div class={s.cards}>
          {features.map((feature) => (
            <div class={s.card} key={feature.key}>
              <p class={s.cardKey}>{feature.key}</p>
              <h3 class={s.cardTitle}>{feature.title}</h3>
              <p class={s.cardText}>{feature.text}</p>
            </div>
          ))}
        </div>
      </div>
    </section>

    <section class={s.sectionAlt} id="how">
      <div class={wrap}>
        <p class={sectionTag}>How it works</p>
        <h2 class={sectionTitle}>Four parts. One contract.</h2>
        <p class={lede}>
          The proto under <code>proto/peculiar/insights/v1</code> is the single source of truth for
          every language. Generated messages travel unchanged into the SDKs, and every collected
          field carries its data category and consent purpose.
        </p>
        <Diagram />
        <div class={s.steps}>
          <div class={s.step}>
            <p class={s.stepNumber}>01</p>
            <h3 class={s.stepTitle}>The SDK batches.</h3>
            <p class={s.cardText}>
              Client-generated UUIDs, a sent-at timestamp for clock skew, and the consent snapshot
              on every batch. At least once, exactly once in effect.
            </p>
          </div>
          <div class={s.step}>
            <p class={s.stepNumber}>02</p>
            <h3 class={s.stepTitle}>The server decides.</h3>
            <p class={s.cardText}>
              Validation, consent enforcement, deduplication, identity merge and crash grouping,
              item by item, with a per-item outcome.
            </p>
          </div>
          <div class={s.step}>
            <p class={s.stepNumber}>03</p>
            <h3 class={s.stepTitle}>PostgreSQL keeps it.</h3>
            <p class={s.cardText}>
              Monthly partitions, per-project retention, a reporting schema of views and functions,
              and admin functions for triage and erasure.
            </p>
          </div>
          <div class={s.step}>
            <p class={s.stepNumber}>04</p>
            <h3 class={s.stepTitle}>Grafana shows it.</h3>
            <p class={s.cardText}>
              A read-only role over the reporting schema, provisioned dashboards and alerts, no
              community plugins.
            </p>
          </div>
        </div>
      </div>
    </section>

    <section class={s.section} id="sdks">
      <div class={wrap}>
        <p class={sectionTag}>SDKs</p>
        <h2 class={sectionTitle}>One vocabulary in four places.</h2>
        <p class={lede}>
          Two objects everywhere: <code>Insights</code> is the process, <code>Tracker</code>{" "}
          records. A tracker is an immutable value; <code>with</code> (<code>with_</code> in Dart)
          derives a child whose properties fold into everything it records.
        </p>
        <div class={s.vocabulary}>
          {vocabulary.map((word) => (
            <span class={s.chip} key={word}>
              {word}
            </span>
          ))}
        </div>
        <div class={s.codeGrid}>
          <div class={s.codeBlock}>
            <h3 class={s.codeTitle}>Flutter</h3>
            <pre class={s.pre}>
              <code>{flutterSample}</code>
            </pre>
          </div>
          <div class={s.codeBlock}>
            <h3 class={s.codeTitle}>Haskell</h3>
            <pre class={s.pre}>
              <code>{haskellSample}</code>
            </pre>
          </div>
        </div>
        <div class={s.cards}>
          {sdks.map((sdk) => (
            <div class={s.card} key={sdk.title}>
              <h3 class={s.cardTitle}>{sdk.title}</h3>
              <p class={s.cardText}>{sdk.text}</p>
            </div>
          ))}
        </div>
      </div>
    </section>

    <section class={s.sectionAlt} id="principles">
      <div class={wrap}>
        <p class={sectionTag}>How it is built</p>
        <h2 class={sectionTitle}>Principles, not promises.</h2>
        <div class={s.principles}>
          {principles.map((principle) => (
            <div class={s.principle} key={principle.key}>
              <p class={s.cardKey}>{principle.key}</p>
              <h3 class={s.cardTitle}>{principle.title}</h3>
              <p class={s.cardText}>{principle.text}</p>
            </div>
          ))}
        </div>
      </div>
    </section>

    <section class={s.section} id="start">
      <div class={wrap}>
        <p class={sectionTag}>Start</p>
        <h2 class={sectionTitle}>Deploy it, then hand the guide to an agent.</h2>
        <div class={s.cta}>
          <h3 class={s.ctaTitle}>Read the docs</h3>
          <p class={s.ctaText}>
            Deploying with NixOS, the Grafana dashboards, operations, the consent model, and a
            document written for an agent to integrate the SDKs into your product.
          </p>
          <div class={s.ctas}>
            <a class={button} href="/docs">
              Documentation <span aria-hidden="true">→</span>
            </a>
            <a class={buttonGhost} href="/docs/agents">
              For agents <span aria-hidden="true">→</span>
            </a>
          </div>
        </div>
      </div>
    </section>
  </>
);
