[package]
name = "peculiar-insights-symbolicator"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
proguard = "5"
prost = "0.14"
sourcemap = "9"
symbolic = { version = "13", default-features = false, features = ["debuginfo", "demangle", "symcache"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.14"
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
